services:
  database:
    image: postgres:17
    volumes:
      - database_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: paul
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: paul
    ports:
      - 0.0.0.0:5432:5432
  server:
    image: node:23-alpine
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: yarn start
    ports:
      - 0.0.0.0:3000:3000
    depends_on:
      - database

volumes:
  database_storage:
